### ISSUE TITLE
Search returning "None" for every search as of 5/19/21

### ISSUE THREAD

**Issue by bellerson** [ScrappyCocco/HowLongToBeat-PythonAPI#10]
Hello, 

Last year I put together a little script for myself using this library so that I could search for HLTB times via the terminal without having to fire up a browser. My last change to my script was in December 21 - I haven't updated it since, but I have been using it since then with no issues.

However, today when I tried to use it, I'm getting "None" for every search I try, even when I know there should be results (my script uses the default matching threshold of 0.4). For example, "Pokemon" returns "None", and then there's nothing to display of course. 

I dug into the source code of the library itself a little bit. In **HTMLRequests.py** it looks like using "search_results.php" in the SEARCH_URL (as is the standard the library comes with) returns a 404 response code. So I'm guessing something has changed on HLTB's side?

I was able to get a 200 response code by updating SEARCH_URL to use "#search" instead, but then I was still not getting any search results no matter what I tried. So whatever's going on is a little beyond what I can solve for myself, unfortunately.

Hoping this doesn't mean the end of this library. Any help would be greatly appreciated.

**Comment by ScrappyCocco** [comment]
Hi @bellerson , you are right the API no longer works, thank you for letting me now

From a first look it looks like is sending the request to this url instead of the previous "search_results.php"
![image](https://user-images.githubusercontent.com/11294898/169476763-d2e808b3-b7a3-4036-9dd2-251e18f62a2a.png)
but I was not ableto figure out and fix the problem yet, since every request I try to send returns as 404, even if all the parameters looks correct

I might be busy this weekend so I'll investigate this problem next week, feel free to do some tests if you want
I'll let you know as soon as I figure something out

**Comment by ScrappyCocco** [comment]
Changing the request like this seem to make it work, but a few test in the test suit still fail so there's something more to fix about getting the game name

![image](https://user-images.githubusercontent.com/11294898/169708532-cdd17341-dfa6-4a6a-af89-6d7a6677d577.png)

**Comment by ScrappyCocco** [comment]
@bellerson fixed, you can update to version 0.1.20, please let me know if you still have any issue
